export const TIPO_ESCOLA = {
  PUBLICA: 'PÚBLICA',
  PRIVADA: 'PRIVADA',
};

export const TIPO_MONITORIA = {
  PRESENCIAL: 'PRESENCIAL',
  REMOTO: 'REMOTO',
};

export const FORMACAO_PROFESSOR = {
  GRADUACAO: 'GRADUAÇÃO',
  ESPECIALIZACAO: 'ESPECIALIZAÇÃO',
  MBA: 'MBA',
  MESTRADO: 'MESTRADO',
  DOUTORADO: 'DOUTORADO',
  POS_DOUTORADO: 'PÓS-DOUTORADO',
};

export const ROLES = {
  ADMIN: 'ROLE_ADMIN',
  PROFESSOR: 'ROLE_PROFESSOR',
};
